version: '3.4'

services:
  budget:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
  sqlserverdb:
    container_name: sqlserverdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong@Passw0rd123"
      MSSQL_PID: "Express"  # Express / Developer / Standard
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Strong@Passw0rd123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
